In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:

import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
import duckdb
import os

class DataLoader():

    def __init__(self, base_url='gs://clusterdata_2019_a', threads=None, max_workers=None):
        self.base_url = base_url
        # max_workers × threads ≈ 2x number of CPU cores; assuming 10 cores
        num_cpus = os.cpu_count()  # logical cores
        self.threads = threads or max(1, num_cpus // 4)
        self.max_workers = max_workers or max(1, num_cpus // self.threads)


    def parallel_load(self, fn, shards=0, max_workers=None, batch_size=10, **kwargs) -> pd.DataFrame:
        '''
        function to run another function (that returns a dataframe) across concurrent futures.
            args :
                fn : function which will be executed by concurrent futures
                shards : number of shards we want to read from the gcs bucket
                max-workers : number of parallel workers
                batch_size : read shards in batches of batch_size\
        '''
        max_workers = max_workers or self.max_workers
        batches = list(range(0, shards, batch_size))  # [0, 10, 20, ...]
        results = [None] * len(batches)
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futs = {
                ex.submit(fn, start, min(start + batch_size - 1, shards - 1), **kwargs): i
                for i, start in enumerate(batches)
            }
            for fut in as_completed(futs):
                i = futs[fut]
                results[i] = fut.result()
                print(f"batch {i+1}/{len(batches)}")
        return pd.concat(results, ignore_index=True)


    def dck_db_load(
                      self,
                      shard_range_start=None,
                      shard_range_end=None,
                      query=None,
                      cols=None,
                      target_collection_ids=None,
                      target_instance_indexes=None,
                      target_pairs=None
                      ) -> pd.DataFrame:

        '''
        function to initialize a duckdb connection and query shards between 'shard_range_start' and 'shard_range_end' from gcs bucket.
        args:
            shard_range_start : start reading shards from here
            shard_range_end : stop reading here
            query : string containing the query to run
            cols : string containing comma separated cols to pull (goes inside the query)
            target_collection_ids : string containing comma separated collection ids to filter on (goes inside the query)
            target_instance_indexes : string containing comma separated instance idxs to filter on (goes inside the query) // this might probably be removed
            target_pairs : string containing comma separated pairs of (collection_id, instance_index) to filter on (goes inside the query)
        '''
        assert shard_range_start is not None, "shard_range_start cannot be None"
        assert shard_range_end is not None, "shard_range_end cannot be None"
        assert query is not None, "query cannot be None"
        assert cols is not None, "cols cannot be None"
        if (query == 'instance_usage') | (query == 'collection_events'):
          assert target_collection_ids is not None, "collection_ids cannot be None"
        if query == 'instance_usage':
          assert target_instance_indexes is not None, "instance_indexes cannot be None"
        if query == 'instance_usage_1':
          assert target_pairs is not None, "instance_pairs cannot be None"

        con = duckdb.connect()
        con.sql("INSTALL httpfs; LOAD httpfs;")
        con.sql(f"SET threads = {self.threads};")

        try:
            dfs=[]
            print(f"processing {shard_range_start} to {shard_range_end}...")
            for i in range(shard_range_start,shard_range_end+1):
                char = str(i).zfill(5)
                print(f"processing {char}...")

                query_set = {
                    'collection_events' : f"""
                            SELECT {cols}
                            FROM read_parquet('{self.base_url}/collection_events-0000000{char}.parquet.gz')
                            WHERE collection_id IN ({target_collection_ids})
                            LIMIT 10000
                        """,
                    'instance_events' : f"""
                            SELECT {cols}
                            FROM read_parquet('{self.base_url}/instance_events-0000000{char}.parquet.gz')
                            WHERE collection_id IN ({target_collection_ids})
                            --LIMIT 10000
                        """,
                    'instance_usage' : f"""
                            SELECT {cols}

                            FROM read_parquet('{self.base_url}/instance_usage-0000000{char}.parquet.gz')
                            WHERE collection_id IN ({target_collection_ids})
                            AND instance_index IN ({target_instance_indexes})
                            ORDER BY collection_id, instance_index, start_time
                            --LIMIT 10000
                        """,
                    'instance_usage_1' : f"""
                            SELECT {cols}
                            FROM read_parquet('{self.base_url}/instance_usage-0000000{char}.parquet.gz')
                            WHERE (collection_id, instance_index) IN ({target_pairs})
                            ORDER BY collection_id, instance_index, start_time
                            --LIMIT 10000"""
                }

                #change query here
                df = con.sql(query_set[query]).df()
                dfs.append(df)
        finally:
            con.close()

        return pd.concat(dfs, ignore_index=True)

In [5]:
DATA_DIR = "/content/drive/MyDrive/Bayesian Final Project/DATA"
coll_events = pd.read_parquet(f"{DATA_DIR}/collections_per_priority_parquet.parquet")
coll_events.head(1).T

                             0
collection_id     382836131204
user              unknown_user
priority                   107
scheduling_class             0
num_instances                9
evictions                    0
failures                     1
kills                        0
finished                 False
outcome                 failed
priority_bin                 2

In [10]:
_collection_ids_unique = coll_events.collection_id.unique()
print(len(_collection_ids_unique))
target_collection_ids = ",".join(_collection_ids_unique.astype(str))
target_collection_ids

1200

'382836131204,383851959840,381105478433,380756707566,399482865043,399595493272,399280623256,381985747703,383224655865,380107214785,383175726451,399880512375,382871403557,383288833095,383502500032,382339850817,383245376450,399280603720,383935187161,396209193336,384616375362,383853127716,399880499837,381151741072,383102456494,19542402683,383584132824,380128692299,383168330598,399880611953,399280626615,383162438237,380756796946,382834274636,383119912850,383049387956,385644689424,380190242235,381589971505,383057854399,382178778804,380756847257,395095968041,393986415502,381781266242,383097010648,399281639261,383007226500,383220010638,384347908201,383934960446,383580277494,382182022963,382985046393,382975382187,383109339182,383102454915,383934961871,383596564347,399595450937,383167913696,383187485657,381781273742,382186799401,383190825959,383057481410,394286938508,399880782949,383149589472,399280604220,399880682150,399880602964,382916261356,382866558237,384345846007,381897833000,399280603892,380190067779,399929039077,385557363455,380199767914,383595410960,399280620811,381105483185,383150787427,382958105992,383838282406,399880868386,385561094533,397258870298,380713104576,383189038410,393986297654,399280605712,380756890811,383168097526,382937678983,382998279180,383149587877,397901138025,382482933322,384765574864,280521931310,319964021976,374580931839,374890387372,374709148602,393975306106,384942377251,375653659089,381007812493,360439471976,376671142722,374890387616,329067143433,360222468477,320180842771,300125081705,381007812567,372915315247,385577013967,142578684328,385607195737,350880623035,384764357277,398975138702,297455193430,300125039260,280487004463,395367156294,360885315987,280487004520,395376363605,376731604876,377969673340,398499177757,397854529503,33339333439,395367156402,384557110608,360222468040,319964010704,374486817999,395284849597,383607144052,360232447530,297455192560,394101287536,359235111864,301297312669,372915315138,395488266950,384021782400,360782401810,327785239957,378150139754,398450239752,188867335323,348725139763,385583417072,319964021873,381007811951,374486819928,327784218316,374860068518,374890387718,372455120985,142579794135,377146695916,380310668107,360782402435,350880622709,350880622464,383897844467,142622461714,360232447455,375551191748,379244011793,393290821590,397283356370,142645877028,282689156728,384281527419,142573338084,299965337333,359235111733,375653658951,385629722067,142591127592,383607143952,394453278414,393289676290,372915315052,360885315658,383897844767,360439471990,383935877706,374486819882,398975138386,377808351694,378633362703,399280582035,378598864618,378599354855,378606717316,378740282161,381667739860,379181955875,378909924281,89163545215,379169158034,378757082967,377800003738,259837246585,378350298729,100548594232,377815025643,399280582526,378718852258,259837270668,400069950079,374860314079,394104477829,379292584878,259837264860,259837260950,378263868731,394143462139,393627082068,379432985057,378363322965,385561092488,378908972968,378508700885,378031865881,378747421355,378203789281,378746124313,379373862729,84700535897,378726054717,378670711616,377805193089,378757380044,379240858448,400323655801,383603753476,379204645451,395344433888,383090349201,378607242419,379081882222,343642972012,378734525705,378826571725,377788301589,378733378098,378316720609,378726579826,378749911194,359246123018,359246123852,377826836583,378312236225,385691800116,102944072177,377874983198,378865188910,383608988795,399394109004,395334908125,377835740052,378201438173,393627081313,379168974011,399952406291,378365997957,378625645463,399280582300,399280591105,377969528425,247429479332,377797319739,383222133415,378698417814,259837769991,259837260882,378412275826,350084572141,376389286134,399394109049,377810330705,398939281050,399394109323,378636219407,377971653942,379039774429,359246027880,378652854144,259837768464,384911606428,399698246237,400451883152,393233377660,383819283749,385557533267,397172223091,376972640483,382720638714,385577688998,380191860635,397214598229,395237830493,377751437634,385244237014,380243924497,390090472199,399943170000,383851356164,384033118998,399407675601,379162563581,330587125888,396843577254,381207467028,377742747486,384460305792,400000842104,380927334169,384150795735,393987570761,387745355601,384563186182,381929068220,385206857131,382338269697,381291227711,395394359304,383327943992,399928999273,378411263786,380549754179,385444057554,380226200115,385235996368,392194172458,383596530690,397196772129,383593087180,381458896815,399633332950,383027097021,384549287558,380091829273,397159286953,384915069015,382725071651,383449317440,398276052577,381927910835,383935120214,381919134323,378559530734,398006982996,378636115775,400365281018,380689174616,395368768818,383347274941,385499666986,397619274230,382750561700,398832591746,383661132229,381105542107,380165430274,382374685146,395293365256,400323381292,383077488630,380682181382,384216161292,399306486212,393591230542,399766638037,390913237619,393659398473,379242891314,400397240523,400421968266,398871828723,378468470014,382911260794,384446634173,385576963018,382323244301,400197605536,379424253649,385706085082,377918480940,379476361797,375996701696,394104360291,382407971135,385493921189,393952717747,396028910784,383176086397,376749620542,399718357762,399529345979,397994457853,399868700911,393580670936,381285799389,398771757024,398476128058,377608499898,394109111027,378716645984,384071477836,378400902324,383540065777,381304671434,398665152858,385539859910,396940879478,377087914196,379086412521,382812761819,398031084931,400204845936,383838688356,378720918734,400457712215,378369296033,384622064825,396899355473,380720287709,380315862563,398042241573,383401807622,380940859240,394454960277,377723003204,383900627150,381403007351,393210289263,379753297525,400460420344,385490470474,399854942915,383883048534,396192124778,400066474261,382239289125,385260760192,389866200564,382845961410,385487801366,381903528780,382324461057,383032379684,396206707914,384319002381,381510702538,396942768486,384486442324,383672214007,396027914759,383393553464,383590528581,381641294720,384997928600,378757961951,384180328850,383820671045,382395507363,375885242070,380804288187,385139367142,399372770927,385476066782,381243128683,397814753742,384919675728,397904138983,385236277142,379232567720,377444330139,379490047096,378757116555,380107317680,391936318305,378634906578,382723719202,395833687752,399497444948,380652963851,382801915227,382380638312,382119823255,376652643310,381576770847,379245757587,382719035022,378727067964,383525525244,383860999467,381586434228,384193954996,383660841308,382985706277,382607097044,380893812459,380794728486,381800363836,382119889898,379510158522,375374269311,375004988288,378758066909,379420271130,382433067210,375092079640,375093509084,375077679791,384912614732,385379460535,381064366538,382605930668,381768810850,383461611736,382939149380,376402398465,381058042902,379465270557,382624408993,400371196120,384420821593,375198747475,385499352122,381670372161,383507154921,380719522263,383898244878,384945361141,383168913541,375341299250,382815320443,383080501388,375254923307,381998495298,393548015715,389369476669,381992416851,380703130527,383216194558,380008937356,381630575387,378743535321,378658518898,383601268295,384265366725,381241941535,383822318840,393196398280,379522223347,380703425401,383860337068,393192001303,381658647131,382802346086,383591079790,379534177574,379482977410,383871562292,375070972107,383959738241,396828206486,380709536213,384186515418,381997722638,382134414983,382108831643,385172951150,399456678535,379516026036,384185927717,381925450721,375195100846,381598347655,383877972520,381063202379,399771470178,383515010334,386889950595,393916320999,375026695554,383863426384,380766951365,381920586861,383100744638,382675429185,397999388782,381577042942,380566184017,399342645177,376807977449,378410928724,379494742972,400131486367,383097929652,381959146747,384924816557,399819124244,399522038497,383545291320,380241091018,385228696644,375078072976,393626879200,399368768785,383462711556,383540077369,381896866878,399528500240,397169729667,388807426225,397619339412,382384541490,383383963458,382466519265,376437985243,395390674793,395307717468,384787805432,378753535043,376193174352,398615586102,385253438309,376682269137,395303497810,381859136070,381403320496,380205778123,398592218999,383845661176,384573845979,381023887097,382735144862,383109202838,381604524544,382533827354,400276348084,399408821168,394046039580,379981830865,396066255922,385653706358,378672766799,398912547761,396080657133,380598956123,399482782874,398597720806,383189498850,395292721637,384925538655,393573357556,380756892548,389401559530,383200584589,380959062402,384243953296,379473327263,379424099957,374840673804,378088415427,382863700795,391796545259,382965859273,397154533175,383852385369,399633924652,384180252834,393188817306,393126651196,393986409888,379515830922,400463175153,381645151704,383428653118,382675441193,382893641978,380895973593,398278319062,385073655573,383206601471,397716167146,379336292584,378722864758,393630174359,377780678364,377805198100,384728973201,393185409015,376736245237,399314798882,375034141300,383120313181,376804268112,386095700632,398929922149,381609417918,360229350806,380566802618,375884944000,382937382789,380708828221,375064888137,360232446682,382794255478,381814187757,382426572514,397903478774,395340211753,395293482829,385652816727,393271085806,384911852732,400285283886,382901486630,395322259484,380692798473,399855718719,394677679608,385013464146,390856674883,399643972319,378469333527,360232510387,381049758131,382952680216,382603998427,311086139235,385588208616,382363046263,378999372272,397221849989,382759111506,379640331494,396569945444,385691780523,383558301633,377798380260,396706578613,384137699463,385659922163,399962871116,375354739070,384945207282,380562425730,380305531455,384912222600,384797595190,376736302909,382425087630,385518855922,374675831406,394743212164,399057988842,384756080921,378784406360,360229353445,379602503541,398722884658,396066882499,400122219490,392369568615,384468077610,383448670470,380299680861,396241155119,381625520116,385279907987,395263118265,382741467329,383170760443,378599606140,394128407831,378660207183,383817088309,381878804062,382159398404,377551172441,381912019590,385235907075,378512848688,377757530847,379650815142,375065418212,395935959077,400342033845,400156983012,384958406418,396222726751,378726912250,398021399630,394138455008,398929794023,278289881277,380187205459,69261780153,398903148791,378365967119,400451472799,397178202446,394910122413,374974566334,383912753352,396181772425,397162272353,361022904282,83852399523,398273753529,399834446356,160332828370,398017249335,394838910128,376387274978,378944405162,381289436295,400070157531,398902825595,128325471161,384595929397,379419249545,380202450748,378254182727,376404451137,381928590503,396117014838,376385673063,378096224537,95625556890,379863909201,399423359982,375858626889,400176751073,399551160131,396207035519,375039307654,398127460289,394108352551,380726066515,394253578844,379490929577,384602560261,375430773793,143409504527,375877170896,393040141339,379516794025,394144427022,393644297311,393848896110,399862674057,393916609716,375997302817,393566769125,383408023191,395305554038,397221692131,18438453718,384270931615,374916617575,379572444885,387895752140,385256940345,400260989300,399584369577,395440444015,385641403941,382597684921,396240229783,398041203835,400223434889,379491077330,380248082790,11635820935,400302939809,375076830596,394141886462,398153430398,387207234778,399882131403,384421979741,398009608228,385561092265,382393592978,380449848515,383390115560,382728594864,384289005546,396212752715,378592122761,394941375838,394108934203,376260833982,377794868633,385079151434,393584074900,385468428424,385699785603,377757215638,400318843666,393629093090,376470507940,383878198070,384548602123,380354734213,380516592739,380861591258,382728142497,381781622013,397205680541,400025363371,384272270960,400323356586,385217044240,382718929799,397561504307,380250891945,377383273622,383431929602,383308236398,378661984058,396844312339,380987797005,398410923859,396673746790,381935730615,399807921655,384163506849,377836445623,393187411126,375879794234,394141289067,383689008406,375046757835,377801286137,383991660659,382305492675,383005881891,399945756812,399423820477,400393245454,382998976002,378720773134,381929083558,397999345410,397661413698,377764439136,385577082675,381888032702,381010409817,399626651718,385518484480,400451622998,399132055300,380332794230,380808868126,382543157924,383838414525,380082631591,381888752161,379293345183,398996425778,382195534279,396943361998,397163250259,393627081536,377757826994,382333678273,393622178356,376374327305,398893312625,399550852686,383102904654,384232913995,383823711202,384097216514,393559692230,381941820467,381291338345,399527993892,393586380422,382768922494,379755191332,385557115831,380226590364,384481809184,384922603144,399807373885,376470558055,380678465232,382942132297,375064725358,382407717918,393568920836,398747832477,375381120560,396234969966,394043942246,398652739663,397374601176,380959082746,375046814878,380760107282,398088032795,377874673065,384287285470,382626531054,395335173054,69067658743,385636055395,373143091565,383110816590,381065680285,382740092311,378263795893,383826901090,399847404681,383668770831,394911214086,384846501024,399340404133,385472715561,384028218052,395115429694,383388521920,376743646216,400020229847,389547243783,381184484050,379754663973,398948655781,225929208307,382316071157,375203041244,385603791375,376739864511,397043244877,396244766795,382545663062,375139231848,381745010594,380330723728,383154204325,377785429024,378369252146,380568347444,389197623545,382707573257,377828307512,395488184791,399762954496,398066592999,384137255842,382754891730,394677498163,380726055737,380726903540,400105868034,398970469612,381985410007,393958077860,383435546333,378465352822,395886424563,397981380271,381916547146,383846855857,381898798672,381923515015,396065648588,394044524445,383614404429,385711855842,383858666340,385201918855,384987502663,393936746701,394060409835,384602169221,377756225804,396235056974,385700084466,90419048675,398913149992,395335228985,399742281925,378614511094,399636114558,396247598069,400204872913,397275155796,400226851147,399642743685,394912918953,375065371471,204973518903,382757716563,398054985628,396899192117,394104573418,399920764658,381994946622,397770795052,393263571166,376405994307,383169496985,394001633607,384972198511,379751186607,397903530782,145849276153,379455914156,378266168603,376323496318,394127888097,383604849272,398196263856,380226088448,378720449942,376448843265,394446403856,381992878774,375877207083,380837641925,381146906065,378411001477,385487762399,377751220999,394054617742,380392065566,395488119650,381241775385,400080230910,383032143035,399794216126,399557096456,383427995279,400414902530,398525942089,384568357286,384642371738,397726811036,380197322507,382311844593,385459027929,399855240290,399697970082,375928730155,383837200986,382608863664,400170529532,9941075899,400037053607,379473555366,395781442143,383065878742,383838251322,381016812871,113812359317,387898895208,383837671076,380242331337,399038694301,396246802643,381625621280,380241317871,393190699766,397663714712,375098363433,399438506487,400069981470,397292440630,395893576251,384972172123,379466228815,399479932346,394152054104,388275585534,399645461661,385098563002,399750520782,382098928806,394140810604'

In [11]:
# sample : pulls 10 shards, in default batches of 10, gets cols collection_id and priority from collection id
dl = DataLoader()
df = dl.parallel_load(dl.dck_db_load, shards=10, query='instance_events', cols='collection_id, instance_index, time, type', target_collection_ids=target_collection_ids)

processing 0 to 9...
processing 00000...
processing 00001...
processing 00002...
processing 00003...
processing 00004...
processing 00005...
processing 00006...
processing 00007...
processing 00008...
processing 00009...
batch 1/1

In [12]:
df.to_parquet(f"{DATA_DIR}/instance_events_training01_parquet.parquet")

In [13]:
df = pd.read_parquet(f"{DATA_DIR}/instance_events_training01_parquet.parquet")

In [14]:
df.shape

(125586, 4)

In [15]:
df.groupby(['collection_id', 'instance_index','time']).size()

collection_id  instance_index  time
9941075899     4               55847243279      1
               5               1230403923656    1
               8               586839859943     1
                               2616883466849    1
               9               405828165600     1
                                               ..
400460420344   446             2677711878678    1
               478             2677700156461    1
               480             2677736479379    1
               485             2677712208676    1
400463175153   4               2678224046330    1
Length: 124850, dtype: int64

In [27]:
df2 = df[["collection_id", "instance_index", "time"]].copy()

# Ensure integer dtype (helps speed + avoids object groupby)
df2["collection_id"] = pd.to_numeric(df2["collection_id"], errors="coerce").astype("Int64")
df2["instance_index"] = pd.to_numeric(df2["instance_index"], errors="coerce").astype("Int64")
df2["time"] = pd.to_numeric(df2["time"], errors="coerce").astype("Int64")
df2 = df2.dropna()

# -----------------------------
# 1) detect unix unit (override if you already know it)
# -----------------------------
mx = int(df2["time"].max())

time_unit = "us"


print("Detected time unit:", time_unit, "| max time:", mx)

# -----------------------------
# 2) aggregate per (collection_id, instance_index)
# -----------------------------
agg = (
    df2.groupby(["collection_id", "instance_index"], sort=False, observed=True)["time"]
       .agg(time_min="min", time_max="max", n_rows="size")
       .reset_index()
)

# span in raw units + as timedelta
agg["span_units"] = agg["time_max"] - agg["time_min"]
agg["span"] = pd.to_timedelta(agg["span_units"].astype("int64"), unit=time_unit)

# -----------------------------
# 3) top 10 by longest duration
# -----------------------------
top50 = (
    agg.sort_values(["span_units", "n_rows"], ascending=[False, False])
       #.head(1000)
       .reset_index(drop=True)
)

# Optional: nicer HH:MM:SS (includes days if needed)
top50["span_hhmmss"] = top50["span"].astype(str)

# Select the columns you asked for
top50 = top50[["collection_id", "instance_index", "n_rows", "span", "span_units" ]] #, "span_hhmmss", "time_min", "time_max"]]

display(top50.head(1000))

Detected time unit: us | max time: 2678983818889

,collection_id,instance_index,n_rows,span,span_units
0,330587125888,29,37,31 days 00:07:42.059528,2678862059528
1,280487004463,0,538,31 days 00:04:51.905633,2678691905633
2,259837769991,0,547,30 days 23:58:53.361288,2678333361288
3,330587125888,1360,19,30 days 23:56:56.216278,2678216216278
4,301297312669,0,536,30 days 23:55:01.576675,2678101576675
...,...,...,...,...,...
995,330587125888,1444,11,29 days 03:22:28.708453,2517748708453
996,330587125888,857,15,29 days 03:16:10.959154,2517370959154
997,330587125888,2373,7,29 days 03:15:31.543702,2517331543702
998,330587125888,1350,10,29 days 03:15:02.723725,2517302723725
999,330587125888,683,27,29 days 03:14:13.403942,2517253403942

In [28]:
top50['span_units'].describe()

count                41063.0
mean     187344746780.158569
std       607692517941.44519
min                      0.0
25%                      0.0
50%                      0.0
75%                      0.0
max          2678862059528.0
Name: span_units, dtype: Float64

In [39]:
_top50 = top50[top50['span_units'] > 0].copy()
_top50.shape

(7061, 5)

In [40]:
_jdf = pd.merge(_top50, coll_events, on=['collection_id'], how='left')

In [41]:
#_jdf.head(1).T
_jdf.groupby(['priority_bin', 'outcome']).size()

priority_bin  outcome
2             failed          919
              finished       2580
              manual_kill     366
              other            33
3             failed          333
              finished         48
              manual_kill     476
              other            27
4             failed          402
              finished        114
              manual_kill    1737
              other            26
dtype: int64

In [42]:
sampled_jdf = _jdf.groupby(['outcome', 'priority_bin']).apply(lambda x: x.sample(n=min(100, len(x)), random_state=42)).reset_index(drop=True)
display(sampled_jdf.head())

/tmp/ipykernel_10927/1783610777.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_jdf = _jdf.groupby(['outcome', 'priority_bin']).apply(lambda x: x.sample(n=min(100, len(x)), random_state=42)).reset_index(drop=True)

,collection_id,instance_index,n_rows,span,span_units,user,priority,scheduling_class,num_instances,evictions,failures,kills,finished,outcome,priority_bin
0,399280623256,758,2,0 days 03:56:15.838407,14175838407,unknown_user,103,1,88,0,19,0,False,failed,2
1,399280623256,1485,2,0 days 03:26:12.150615,12372150615,unknown_user,103,1,88,0,19,0,False,failed,2
2,399280623256,108,3,0 days 02:14:07.383280,8047383280,unknown_user,103,1,88,0,19,0,False,failed,2
3,399281639261,311,2,0 days 02:06:56.536742,7616536742,unknown_user,103,1,98,0,21,0,False,failed,2
4,399280605712,979,2,0 days 00:20:30.691075,1230691075,unknown_user,103,1,100,0,24,0,False,failed,2

In [43]:
sampled_jdf.groupby(['priority_bin', 'outcome']).size()

priority_bin  outcome
2             failed         100
              finished       100
              manual_kill    100
              other           33
3             failed         100
              finished        48
              manual_kill    100
              other           27
4             failed         100
              finished       100
              manual_kill    100
              other           26
dtype: int64

In [44]:
_target_collection_ids = ",".join(sampled_jdf.collection_id.astype(str).to_list())
_target_instance_indexes = ",".join(sampled_jdf.instance_index.astype(str).to_list())

In [45]:
pairs = list(
    zip(
        sampled_jdf["collection_id"],
        sampled_jdf["instance_index"]
    )
)
pair = list(set(pairs))
target_pairs = ", ".join(
    f"({int(cid)}, {int(iid)})"
    for cid, iid in pairs
)

In [46]:
cols = '''start_time,
        collection_id,
        instance_index,
        average_usage.cpus as average_usage_cpus,
        average_usage.memory as average_usage_memory,
        maximum_usage.cpus as maximum_usage_cpus,
        maximum_usage.memory as maximum_usage_memory,
        cycles_per_instruction,
        random_sample_usage.cpus as random_sample_usage_cpus,
        random_sample_usage.memory as random_sample_usage_memory,
        assigned_memory,
        page_cache_memory,
        memory_accesses_per_instruction,
        cpu_usage_distribution,
        tail_cpu_usage_distribution'''

In [47]:
dl = DataLoader()

#_instance_usages_df = dl.parallel_load(
    #dl.dck_db_load, shards=1000,
    #batch_size=100, query='instance_usage',
    #cols= cols,
    #target_collection_ids=_target_collection_ids,
    #target_instance_indexes=_target_instance_indexes)

_instance_usages_df = dl.parallel_load(
    dl.dck_db_load, shards=500,
    batch_size=50, query='instance_usage_1',
    cols= cols,
    target_collection_ids=None,
    target_instance_indexes=None,
    target_pairs = target_pairs)

processing 0 to 49...
processing 00000...
processing 50 to 99...
processing 00050...
processing 100 to 149...
processing 00100...
processing 150 to 199...
processing 00150...
processing 00051...
processing 00001...
processing 00151...
processing 00101...
processing 00052...
processing 00002...
processing 00152...
processing 00102...
processing 00003...
processing 00053...
processing 00153...
processing 00103...
processing 00004...
processing 00154...
processing 00054...
processing 00104...
processing 00005...
processing 00155...
processing 00105...
processing 00055...
processing 00006...
processing 00156...
processing 00056...
processing 00106...
processing 00007...
processing 00157...
processing 00057...
processing 00107...
processing 00008...
processing 00158...
processing 00058...
processing 00108...
processing 00009...
processing 00059...
processing 00159...
processing 00109...
processing 00010...
processing 00110...
processing 00160...
processing 00060...
processing 00011...
processing 00111...
processing 00161...
processing 00061...
processing 00012...
processing 00112...
processing 00162...
processing 00062...
processing 00013...
processing 00113...
processing 00163...
processing 00063...
processing 00014...
processing 00114...
processing 00164...
processing 00064...
processing 00015...
processing 00165...
processing 00115...
processing 00065...
processing 00016...
processing 00166...
processing 00116...
processing 00066...
processing 00017...
processing 00117...
processing 00167...
processing 00018...
processing 00067...
processing 00118...
processing 00168...
processing 00068...
processing 00019...
processing 00119...
processing 00169...
processing 00069...
processing 00020...
processing 00170...
processing 00120...
processing 00070...
processing 00021...
processing 00171...
processing 00121...
processing 00071...
processing 00022...
processing 00172...
processing 00122...
processing 00072...
processing 00023...
processing 00173...
processing 00073...
processing 00123...
processing 00024...
processing 00124...
processing 00074...
processing 00174...
processing 00025...
processing 00125...
processing 00175...
processing 00075...
processing 00026...
processing 00126...
processing 00176...
processing 00076...
processing 00027...
processing 00077...
processing 00127...
processing 00177...
processing 00028...
processing 00128...
processing 00078...
processing 00178...
processing 00029...
processing 00079...
processing 00129...
processing 00179...
processing 00030...
processing 00080...
processing 00130...
processing 00180...
processing 00031...
processing 00081...
processing 00131...
processing 00181...
processing 00032...
processing 00132...
processing 00082...
processing 00182...
processing 00033...
processing 00083...
processing 00133...
processing 00183...
processing 00034...
processing 00134...
processing 00084...
processing 00184...
processing 00035...
processing 00135...
processing 00085...
processing 00185...
processing 00036...
processing 00136...
processing 00086...
processing 00186...
processing 00137...
processing 00037...
processing 00087...
processing 00187...
processing 00038...
processing 00138...
processing 00088...
processing 00188...
processing 00039...
processing 00139...
processing 00089...
processing 00189...
processing 00040...
processing 00090...
processing 00140...
processing 00190...
processing 00041...
processing 00091...
processing 00141...
processing 00042...
processing 00191...
processing 00142...
processing 00092...
processing 00043...
processing 00192...
processing 00143...
processing 00093...
processing 00144...
processing 00044...
processing 00193...
processing 00094...
processing 00145...
processing 00045...
processing 00194...
processing 00095...
processing 00146...
processing 00046...
processing 00195...
processing 00096...
processing 00147...
processing 00047...
processing 00196...
processing 00148...
processing 00097...
processing 00197...
processing 00048...
processing 00149...
processing 00098...
processing 00049...
processing 00198...
processing 00099...
batch 3/10
processing 200 to 249...
processing 00200...
batch 1/10
processing 00199...
processing 250 to 299...
processing 00250...
batch 2/10
processing 300 to 349...
processing 00300...
processing 00201...
batch 4/10
processing 350 to 399...
processing 00350...
processing 00251...
processing 00301...
processing 00202...
processing 00351...
processing 00252...
processing 00302...
processing 00352...
processing 00203...
processing 00303...
processing 00253...
processing 00353...
processing 00204...
processing 00304...
processing 00254...
processing 00354...
processing 00205...
processing 00305...
processing 00255...
processing 00355...
processing 00206...
processing 00306...
processing 00256...
processing 00356...
processing 00207...
processing 00307...
processing 00257...
processing 00357...
processing 00208...
processing 00308...
processing 00258...
processing 00358...
processing 00209...
processing 00259...
processing 00309...
processing 00359...
processing 00210...
processing 00260...
processing 00310...
processing 00360...
processing 00211...
processing 00311...
processing 00261...
processing 00361...
processing 00212...
processing 00262...
processing 00362...
processing 00312...
processing 00213...
processing 00313...
processing 00363...
processing 00263...
processing 00214...
processing 00364...
processing 00264...
processing 00314...
processing 00215...
processing 00365...
processing 00315...
processing 00265...
processing 00216...
processing 00366...
processing 00266...
processing 00316...
processing 00217...
processing 00367...
processing 00267...
processing 00317...
processing 00218...
processing 00368...
processing 00268...
processing 00318...
processing 00219...
processing 00369...
processing 00269...
processing 00319...
processing 00370...
processing 00220...
processing 00270...
processing 00320...
processing 00371...
processing 00221...
processing 00271...
processing 00321...
processing 00372...
processing 00222...
processing 00272...
processing 00322...
processing 00223...
processing 00373...
processing 00323...
processing 00273...
processing 00224...
processing 00374...
processing 00324...
processing 00375...
processing 00225...
processing 00274...
processing 00376...
processing 00226...
processing 00325...
processing 00275...
processing 00326...
processing 00377...
processing 00276...
processing 00227...
processing 00378...
processing 00327...
processing 00228...
processing 00277...
processing 00379...
processing 00328...
processing 00229...
processing 00278...
processing 00380...
processing 00329...
processing 00230...
processing 00279...
processing 00330...
processing 00381...
processing 00280...
processing 00231...
processing 00382...
processing 00281...
processing 00331...
processing 00232...
processing 00383...
processing 00282...
processing 00332...
processing 00233...
processing 00333...
processing 00384...
processing 00283...
processing 00234...
processing 00385...
processing 00334...
processing 00235...
processing 00284...
processing 00386...
processing 00335...
processing 00236...
processing 00285...
processing 00387...
processing 00336...
processing 00286...
processing 00388...
processing 00237...
processing 00337...
processing 00287...
processing 00389...
processing 00238...
processing 00338...
processing 00288...
processing 00390...
processing 00239...
processing 00339...
processing 00289...
processing 00391...
processing 00240...
processing 00340...
processing 00392...
processing 00241...
processing 00290...
processing 00242...
processing 00393...
processing 00291...
processing 00341...
processing 00292...
processing 00394...
processing 00342...
processing 00243...
processing 00395...
processing 00293...
processing 00343...
processing 00244...
processing 00396...
processing 00344...
processing 00245...
processing 00294...
processing 00397...
processing 00345...
processing 00295...
processing 00246...
processing 00346...
processing 00247...
processing 00296...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

processing 00398...
processing 00347...
processing 00248...
processing 00297...
processing 00348...
processing 00399...
processing 00249...
processing 00298...
processing 00349...
batch 8/10
processing 400 to 449...
processing 00400...
batch 5/10
processing 450 to 499...
processing 00450...
processing 00299...
processing 00401...
batch 7/10
batch 6/10
processing 00451...
processing 00402...
processing 00452...
processing 00403...
processing 00453...
processing 00404...
processing 00454...
processing 00405...
processing 00455...
processing 00406...
processing 00456...
processing 00407...
processing 00457...
processing 00408...
processing 00458...
processing 00409...
processing 00459...
processing 00410...
processing 00460...
processing 00411...
processing 00461...
processing 00412...
processing 00462...
processing 00413...
processing 00463...
processing 00414...
processing 00464...
processing 00415...
processing 00465...
processing 00466...
processing 00416...
processing 00467...
processing 00417...
processing 00418...
processing 00468...
processing 00419...
processing 00469...
processing 00420...
processing 00470...
processing 00421...
processing 00471...
processing 00422...
processing 00472...
processing 00423...
processing 00473...
processing 00424...
processing 00474...
processing 00425...
processing 00426...
processing 00475...
processing 00476...
processing 00427...
processing 00428...
processing 00477...
processing 00429...
processing 00478...
processing 00430...
processing 00479...
processing 00431...
processing 00480...
processing 00432...
processing 00481...
processing 00433...
processing 00482...
processing 00434...
processing 00483...
processing 00435...
processing 00484...
processing 00436...
processing 00485...
processing 00437...
processing 00486...
processing 00438...
processing 00487...
processing 00439...
processing 00488...
processing 00440...
processing 00489...
processing 00441...
processing 00490...
processing 00442...
processing 00491...
processing 00443...
processing 00492...
processing 00444...
processing 00493...
processing 00445...
processing 00494...
processing 00446...
processing 00495...
processing 00447...
processing 00448...
processing 00496...
processing 00449...
processing 00497...
processing 00498...batch 9/10

processing 00499...
batch 10/10

In [48]:
_instance_usages_df.groupby(['collection_id', 'instance_index']).size().describe()

count     712.000000
mean      219.765449
std       602.676410
min         1.000000
25%         6.000000
50%        46.000000
75%       188.250000
max      4793.000000
dtype: float64

In [36]:
_instance_usages_df.to_parquet(f"{DATA_DIR}/instance_usage_training01_parquet.parquet")

In [49]:
_tmp_iu = _instance_usages_df.groupby(['collection_id', 'instance_index']).size().reset_index()

In [53]:
def average_gap_per_collection_instance(df):
    df = df.sort_values(['collection_id', 'instance_index', 'start_time']).copy()
    df['next_start_time'] = (
        df.groupby(['collection_id', 'instance_index'])['start_time']
          .shift(-1)
    )
    df['gap_seconds'] = (
        (df['next_start_time'] - df['start_time']) / 1e6
    )
    result = (
        df.groupby(['collection_id', 'instance_index'])['gap_seconds']
          .mean()
          .reset_index(name='avg_gap_seconds')
    )
    return result

In [51]:
_res = average_gap_per_collection_instance(_instance_usages_df)

In [52]:
_res.avg_gap_seconds.describe()

count       647.000000
mean      13115.938993
std       33069.781848
min           1.000000
25%        2372.533333
50%        5632.000000
75%        9696.511628
max      439888.000000
Name: avg_gap_seconds, dtype: float64

In [31]:
_res.head(1).T

                            0
collection_id    9.941076e+09
instance_index   8.000000e+00
avg_gap_seconds  3.324800e+04

In [32]:
_jdf1 = pd.merge(_res, sampled_jdf, on=['collection_id', 'instance_index'], how='left')

In [33]:
_jdf1.groupby(['priority_bin', 'outcome']).size()

priority_bin  outcome
2             failed          8
              finished        8
              manual_kill     8
3             failed         10
              finished        1
              manual_kill     8
              other           3
4             failed          8
              manual_kill    10
              other           3
dtype: int64